# Generated basic setup using chatgpt
name: CI

on:
  push:
    branches:
      - main
      - '**'  # This will trigger on pushes to any branch
    tags:
      - 'v*'  # This will trigger on version tags

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'  # Change to your desired Go version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - name: Run Go tests
        run: |
          pwd
          cd ..
          git clone  --depth 1 https://github.com/forgetaboutitapp/protobufs
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest    
          sudo apt install just
          dart pub global activate protoc_plugin
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

          cd protobufs
          just
          cd ..
          cd forget-about-it
          just
          go test ./...
          cd ../
          cd frontend
          flutter test

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'  # Change to your desired Go version
      - name: Build provisioning app
        run: |
          pwd
          cd ..
          git clone  --depth 1 https://github.com/forgetaboutitapp/protobufs
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest    
          sudo apt install just
          dart pub global activate protoc_plugin
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

          cd protobufs
          just
          cd ..
          cd forget-about-it/server
          just
          pwd
          echo "about to do full build"
          cd /home/runner/work/forget-about-it/forget-about-it/server
          for os in linux windows freebsd openbsd darwin; do
            for arch in arm64 amd64; do
              mkdir -p  ${{ github.workspace }}/tmp-release/${os}-${arch}
              ext=""
              if [ "$os" == "windows" ]; then
                ext=".exe"
              fi
              GOOS=$os GOARCH=$arch go build --ldflags '-extldflags "-static"' -o ${{ github.workspace }}/tmp-release/forget-about-it-$os-$arch/provision${ext} ./cmd/provision
            done
          done
          cd /home/runner/work/forget-about-it/forget-about-it/server

          for os in linux windows freebsd openbsd darwin; do
            for arch in arm64 amd64; do
              ext=""
              if [ "$os" == "windows" ]; then
                ext=".exe"
              fi
              GOOS=$os GOARCH=$arch go build --ldflags '-extldflags "-static"' -o ${{ github.workspace }}/tmp-release/forget-about-it-$os-$arch/server${ext} ./cmd/server
            done
          done
          mkdir -p ${{ github.workspace }}/releases/
          cd ${{ github.workspace }}/tmp-release/
          for os in linux windows freebsd openbsd darwin; do
            for arch in arm64 amd64; do
              if [ "$os" == "windows" ]; then
                  zip -r ${{ github.workspace }}/releases/forget-about-it-${os}-${arch}.zip forget-about-it-$os-$arch
              else
                tar -czvf ${{ github.workspace }}/releases/forget-about-it-${os}-${arch}.tar.gz forget-about-it-$os-$arch
              fi
            done
          done
          cd /home/runner/work/forget-about-it/forget-about-it/frontend
          mkdir ${{ github.workspace }}/releases
          ls build
          ls build/app
          ls build/app/outputs
          ls build/app/outputs/flutter-apk/
          mv build/app/outputs/flutter-apk/app-release.apk ${{ github.workspace }}/releases/forget-about-it.apk
      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            ${{ github.workspace }}/releases/*